# MultiStage
# Etapas recomendadas por Fernando

## Dependencia
# Esto crea una maquina virtual donde solo estan todos los modulos de node
FROM node:22.22-alpine3.22 AS deps

WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json ./


RUN npm install

## Builder -> Contruye la aplicacion

FROM node:22.22-alpine3.22 AS build

WORKDIR /usr/src/app

ARG PORT
ARG NATS_SERVERS
ARG DATABASE_URL
ARG JWT_SECRET

ENV PORT=${PORT}
ENV NATS_SERVERS=${NATS_SERVERS}
ENV DATABASE_URL=${DATABASE_URL}
ENV JWT_SECRET=${JWT_SECRET}


# Copiar de deps, los modulos de node
# COPY --from=stage origin dest
# NOTA origin es el path donde esta lo que quiero copiar

COPY --from=deps /usr/src/app/node_modules ./node_modules

# Copiamos todo el codigo fuente
COPY . .

# RUN npm run test --> este es el lugar para ejecutar los testing

# esto genera la carpeta generate
RUN npx prisma generate

# esto genera la carpeta dist
RUN npm run build

# Limpieza de modulos o dependencias de node que no se necesitan
RUN npm ci -f --only=production && npm cache clean --force

RUN npx prisma generate

## Crear la imagen final de docker

FROM node:22.22-alpine3.22 AS prod

WORKDIR /usr/src/app

ARG PORT
ARG NATS_SERVERS
ARG DATABASE_URL
ARG JWT_SECRET

ENV PORT=${PORT}
ENV NATS_SERVERS=${NATS_SERVERS}
ENV DATABASE_URL=${DATABASE_URL}
ENV JWT_SECRET=${JWT_SECRET}

# Copiar de build, los modulos de node
# COPY --from=stage origin dest
# NOTA origin es el path donde esta lo que quiero copiar
COPY package.json ./
COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/prisma ./prisma
COPY --from=build /usr/src/app/dev.db ./dev.db


# Muy comun verlo para indicar que estamos en produccion
ENV NODE_ENV=production


# Crea un usuario llamado node y nos movemos a ese usuario es decir el va a ejecutar las lineas siguiente
# esto se hace porque si lo dejamos con el usuario que viene en la imagen (node:22.22-alpine3.22) tiene
# demasiado privilegio
USER node

EXPOSE 3000

CMD [ "node", "dist/src/main.js" ]